<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Checkin extends CI_Controller {

	public function __construct()
   {
		parent::__construct();
		// Your own constructor code
		//$this->load->model('CheckinGame');
   }
	public function index()
	{
		
	}
	
	public function login_process(){
		$data['login_process'] = false;
		$this->load->model('Facebook_Handshaking');
		$ret = $this->Facebook_Handshaking->is_login();
		if ($ret === true){
			if (isset($_GET["state"])){
				// capture the facebook unexpacted redirect
				$this->load->helper('url');
				redirect("http://kit.csie.ntu.edu.tw/CheckinGame/", 'refresh');
				return 0;
			}
				$data["login_process"] = true;
				$data["logout_url"] = $this->Facebook_Handshaking->get_logout_url();
		}else{
			$data["login_url"] = $this->Facebook_Handshaking->get_login_url();
			//$data["login_url"] = preg_replace("/server%2Findex.php%2Fcheckin%2Flogin_process%2F/", "",$data["login_url"]);
			
			//becasue the redirect url generated by api in not our homepage
			//so I make one instead of using php api
			//$redirect_url = urlencode("http://kit.csie.ntu.edu.tw/CheckinGame/");
			//$data["login_url"] = "https://www.facebook.com/dialog/oauth?client_id=198708110184421&redirect_uri=".$redirect_url."&scope=publish_checkins,publish_stream,read_stream";
		}
		echo json_encode($data);
	}
	public function login_check(){
		// want to block the unexpacted connection
		$this->load->model('Facebook_Handshaking');
		$ret = $this->Facebook_Handshaking->is_login();
		return $ret;
	}
	function get_last_question()
	{
		//fake data
		/*
		$data['question_id'] = 1;
		$data['last_location'] = array(
			'x'   => 25,
			'y'   => 32,
			'name'=>'台大資工系'
		
		);
		$data['last_question'] = 
		array
		(
			array('option_id'=>1,'x'=>1,'y'=>2,'name'=>'科技大樓'),
			array('option_id'=>2,'x'=>1,'y'=>2,'name'=>'辛亥隧道'),
			array('option_id'=>3,'x'=>1,'y'=>2,'name'=>'公館捷運站'),
			array('option_id'=>4,'x'=>1,'y'=>2,'name'=>'臺師大')
		
		);*/
		$data['result'] = false;
		$ret = $this->login_check();
		if ($ret === true){
			$this->load->model('Checkin_Game');
			$this->Checkin_Game->last_question();
		}
		echo json_encode($data);
		exit(1);
		
	
	}
	
	function answer_question()
	{
		$question_id = $this->input->post('question_id');
		$option_id = $this->input->post('option_id');
		
		$data['result'] = false;
		$ret = $this->login_check();
		if ($ret === true){
			$this->load->model('Checkin_Game');
			$this->Checkin_Game->answer_question($question_id,$option_id);
			$data['result'] = true;
		}
		//$this->CheckinGame->answer_question($question_id,$option_id);
		echo json_encode($data);
		exit(1);
	}
	function get_gps_inf()
	{
		$x = $this->input->post('x');
		$y = $this->input->post('y');
		$checkin_radius = 100;
		$quection_radius = 10000;
		
		$data['result'] = false;
		$ret = $this->login_check();
		if ($ret === true){
			$this->load->model('Checkin_Game');
			$ret = $this->Checkin_Game->get_gps_page_info($x,$y,$checkin_radius,$quection_radius);
			if ($ret != NULL){
				$data['result'] = true;
				$data["checkin_list"] = $ret["checkin_list"];
				$data["question_list"] = $ret["question_list"];
			}
		}
		echo json_encode($data);
		exit(1);
		
		
	}
	
	function checkin_hook(){
		
		$checkin_page_id = $this->input->post('checkin_page_id');		
		$msg= $this->input->post('msg');
		$questionIDList = $this->input->post('questionIDList');
		$question_page_id = preg_split("/,/",$questionIDList);
		$num = count($question_page_id );

		$errno = 0;
		$data['result'] = false;
		if($checkin_page_id==0) $errno = 1;//for unexecepted err
		else if($num<2) $errno = 2;//for un enough option

		if ($errno != 0){
			$data["errno"] = $errno;
			echo json_encode($data);
			return -1;
		}

		$ret = $this->login_check();
		if ($ret === true){
			$this->load->model('Checkin_Game');
			$ret = $this->Checkin_Game->checkin($checkin_page_id,$msg,$question_page_id);
			if ($ret != false){
				$data['result'] = true;
			}
		}

		echo json_encode($data);
		exit(1);


	}

}

/* End of file checkin.php */
/* Location: ./application/controllers/checkin.php */
?>
